apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /var/log/*.log  # Adjust the path based on your log file locations
      exclude_files: ['\.gz$']  # Exclude compressed log files

    output.elasticsearch:
      hosts: ["http://10.244.94.7:9200"]  # Adjust the Elasticsearch endpoint as needed

    setup.kibana:
      host: "http://10.244.94.12:5601"