apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-external
spec:
  type: NodePort
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30000  # You can choose any available port number
  selector:
    app: elasticsearch
