name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Trigger on pushes to master branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specify the operating system for the runner

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.REPO_NAME }}/${{ secrets.IMAGE_NAME }} .
          docker push ${{ secrets.REPO_NAME }}/${{ secrets.IMAGE_NAME }}:latest

       - name: Install gridscalecloud
         run: |
          curl -sL https://cli.gridscale.io/install.sh | bash
          gscl version

      - name: Set up Gridscale Configuration
        run: |
          echo "${{ secrets.CONFIG_FILE }}" > gridscale-config.yaml && gscloud --config gridscale-config.yaml make-config

      - name: Retrieve Kubeconfig Secret
        run: |
          # Retrieve kubeconfig from secret management service
          # and store it in a file
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/hello-application-kubeconfig.yaml

      - name: Export KUBECONFIG
        run: export KUBECONFIG=~/.kube/hello-application-kubeconfig.yaml

      - name: Deploy to Kubernetes Cluster
        run: |
          kubectl apply -f ${{ secrets.HELLO_APP_DEPLOYMENT }}.yaml
